services:
  - type: web
    name: python-chrome-extension
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: NODE_ENV
        value: production
